- name: Fetch current astronauts 
  hosts: localhost 
  connection: local 
  gather_facts: false 
 
  tasks: 
    - name: GET people in space 
      ansible.builtin.uri: 
        url: http://api.open-notify.org/astros.json 
        method: GET 
        return_content: true 
        status_code: 200 
        timeout: 30 
      register: result 
      retries: 3 
      delay: 2 
      until: result.status == 200 
      changed_when: false 
 
    - name: Save JSON to astros.json 
      ansible.builtin.copy: 
        content: "{{ result.content }}" 
        dest: astros.json 
        mode: '0644' 
